name: Call External Review

on:
  push:
    branches: [ "master", "main" ]

jobs:
  trigger-code-review:
    uses: https://github.com/du-mozzie/ai-code-review/.github/workflows/master-remote.yml@master
    secrets:
      access_token: ${{ secrets.ACCESS_TOKEN }}  # 由调用方传递 Token